### ISSUE TITLE
Navbar on Mobile

### ISSUE THREAD

**Issue by Tyler-Hilbert** [Tyler-Hilbert/casestudy#3]
Hey @daishadavis this is completely unrelated to the case study, but I put a tailwind page with a broken navbar here. It disappears on mobile. Will you figure out why, thanks?

https://github.com/Tyler-Hilbert/casestudy/tree/brokenexample

```
git checkout https://github.com/Tyler-Hilbert/casestudy.git
git checkout brokenexample
```

**Comment by daishadavis** [comment]
@Tyler-Hilbert for some reason the first command isn't working its returning this. 
<img width="570" alt="Screenshot 2024-01-20 at 7 36 02 PM" src="https://github.com/Tyler-Hilbert/casestudy/assets/63072310/fa13a6a1-c013-49b2-ae48-f43fb8f9cc9a">

**Comment by Tyler-Hilbert** [comment]
It should be git clone not git checkout

**Comment by daishadavis** [comment]
@Tyler-Hilbert I'm looking at the nav bar on my phone and it looks like it works for me can you send me a picture of what your seeing.

**Comment by Tyler-Hilbert** [comment]
Check again, I just merged the branch into main so github pages updated

**Comment by daishadavis** [comment]
@Tyler-Hilbert Just pushed my commit see if it works

**Comment by Tyler-Hilbert** [comment]
@daishadavis 
Hey add your fix here
https://github.com/Tyler-Hilbert/OwenAEdwards.github.io

I just gave you collaborator permissions.
Also, can you update the navbar in all 3 .html files?

**Comment by Tyler-Hilbert** [comment]
> @daishadavis Hey add your fix here https://github.com/Tyler-Hilbert/OwenAEdwards.github.io
> 
> I just gave you collaborator permissions. Also, can you update the navbar in all 3 .html files?
@daishadavis more feedback
https://github.com/OwenAEdwards/OwenAEdwards.github.io/pull/1#issuecomment-1902174907

**Comment by daishadavis** [comment]
@Tyler-Hilbert Just pushed my updates to fix the nav bar
